/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PROJETOS.EM.JAVA;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        double respsoma, respsub, respmulti, respdivi, n1, n2;
        int escolha;
        int escolha2 = 0;
        int i = 0;

        System.out.println("-----------Bem vindo a calculadora!-----------");

        while (i < 1) {

            if (escolha2 == 2) {
                break;
            } else {

                System.out.println("\nDigite o primeiro número:");
                n1 = in.nextDouble();
                System.out.println("Digite o segundo número:");
                n2 = in.nextDouble();

                System.out.println("\nQual operação deseja fazer?");
                System.out.println("1 --> Soma");
                System.out.println("2 --> Subtração");
                System.out.println("3 --> Multiplicação");
                System.out.println("4 --> Divisão");
                escolha = in.nextInt();

                switch (escolha) {
                    case 1:
                        respsoma = Soma(n1, n2);

                        System.out.println(n1 + " + " + n2 + " = " + respsoma);

                        System.out.println("\n1--> Continuar");
                        System.out.println("2--> Encerrar");
                        escolha2 = in.nextInt();

                        if (escolha2 == 1) {
                            break;
                        } else if (escolha2 == 2) {

                            break;

                        }
                    case 2:
                        respsub = Sub(n1, n2);

                        System.out.println(n1 + " - " + n2 + " = " + respsub);

                        System.out.println("\n1--> Continuar");
                        System.out.println("2--> Encerrar");
                        escolha2 = in.nextInt();
                        if (escolha2 == 1) {
                            break;
                        } else if (escolha2 == 2) {

                            break;

                        }
                    case 3:
                        respmulti = Multi(n1, n2);

                        System.out.println(n1 + " x " + n2 + " = " + respmulti);

                        System.out.println("1--> Continuar");
                        System.out.println("2--> Encerrar");
                        escolha2 = in.nextInt();
                        if (escolha2 == 1) {
                            break;
                        } else if (escolha2 == 2) {

                            break;

                        }
                    case 4:
                        respdivi = Divi(n1, n2);

                        System.out.println(n1 + "/" + n2 + " = " + respdivi);

                        System.out.println("1--> Continuar");
                        System.out.println("2--> Encerrar");
                        escolha2 = in.nextInt();
                        if (escolha2 == 1) {
                            break;
                        } else if (escolha2 == 2) {

                            break;

                        }

                }
            }
        }

    }

    public static double Soma(double n1, double n2) {

        double soma;
        soma = n1 + n2;

        return soma;
    }

    public static double Sub(double n1,
            double n2) {

        double sub = n1 - n2;

        return sub;
    }

    public static double Multi(double n1,
            double n2) {

        double multi = n1 * n2;

        return multi;
    }

    public static double Divi(double n1,
            double n2) {

        double divi = n1 / n2;

        return divi;
    }

}
